version: 2
registries:
  familie-felles:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/familie-felles
    username: x-access-token
    password: "${{secrets.READER_TOKEN}}"

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    day: "sunday"
    time: "04:00"
  open-pull-requests-limit: 10
  registries:
  - familie-felles
  groups:
    interne-avhengigheter:
      patterns:
        - "no.nav.familie*"
      exclude-patterns:
        - "no.nav.familie.tjenestespesifikasjoner*"
    spring-med-avhengigheter:
      patterns:
        - "org.springframework*"
        - "no.nav.security*"
        - "org.springdoc*"
    prod-avhengigheter:
      dependency-type: "production"
      exclude-patterns:
        - "no.nav.security*"
    utvikler-avhengigheter:
      dependency-type: "development"
      exclude-patterns:
        - "no.nav.security*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: "sunday"
    time: "04:00"
  open-pull-requests-limit: 10
