apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-oppdrag
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8087
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvfamilie-oppdrag
        mountPath: /secret/serviceuser
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: "1"
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-oppdrag.nais.adeo.no
    - https://familie-oppdrag.prod-fss-pub.nais.io
  azure:
    application:
      enabled: true
    accessPolicy:
      inbound:
        rules:
          - application: familie-ks-sak
          - application: familie-ba-sak
          - application: familie-tilbake
            cluster: prod-gcp
          - application: familie-ef-sak
            cluster: prod-gcp
          - application: familie-ef-iverksett
            cluster: prod-gcp
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
