no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: http://mock-oauth2-server:1111/v2.0/.well-known/openid-configuration
    accepted_audience: api://${OPPDRAG_CLIENT_ID}/.default
    cookie_name: azure_token

oppdrag.mq:
  queuemanager: QM1
  send: DEV.QUEUE.1
  mottak: DEV.QUEUE.1
  avstemming: DEV.QUEUE.2
  channel: DEV.ADMIN.SVRCONN
  hostname: mq
  port: 1414
  user: admin
  password: passw0rd
  enabled: true

spring:
  datasource:
    url: jdbc:postgresql://postgres-oppdrag:5432/familieoppdrag
    username: familie
    password: familie-pwd
  cloud:
    vault:
      database:
        role: familie

logging:
  config: "classpath:logback-e2e.xml"

SECURITYTOKENSERVICE_URL: https://localhost:8063/soap/SecurityTokenServiceProvider/
SERVICEUSER_USERNAME: not-a-real-srvuser
SERVICEUSER_PASSWORD: not-a-real-pw
OPPDRAG_SERVICE_URL: #Mockes ut lokalt