# NB! Dette skal ikke skrus på i produksjon før avstemming er på plass!
oppdrag.mq:
  queuemanager: MPLSC02
  send: QA.P_FAMILIE_OPPDRAG.OB04_OPPDRAG_XML
  mottak: QA.P_FAMILIE_OPPDRAG.OPPDRAG_FAMILIE_XML_KVITT
  channel: P_FAMILIE_OPPDRAG
  hostname: a01apvl063.adeo.no
  port: 1414
  user: ${MQ_SRVBRUKER}
  password: ${MQ_PASSWORD}
  enabled: false

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navno.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${CLIENT_ID}
    proxyurl: http://webproxy-nais.nav.no:8088
    cookie_name: azure_token

spring:
  datasource:
    url: jdbc:postgresql://A01DBVL011.adeo.no:5432/familie-oppdrag
