oppdrag.mq:
  queuemanager: MPLS02
  send: QA.P231.OB04_OPPDRAG_XML
  mottak: QA.P_FAMILIE_OPPDRAG.OPPDRAG_FAMILIE_XML_KVITT
  avstemming: QA.P234.OB29_AVSTEMMING_XML
  channel: P_FAMILIE_OPPDRAG
  hostname: a01apvl269.adeo.no
  port: 1414
  user: ${SERVICEUSER_USERNAME}
  password: ${SERVICEUSER_PASSWORD}
  enabled: true

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navno.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${CLIENT_ID}
    proxyurl: http://webproxy-nais.nav.no:8088
    cookie_name: azure_token

ACCEPTED_CLIENTS: ${BA_SAK_CLIENT_ID}, ${EF_SAK_CLIENT_ID}, ${EF_IVERKSETT_CLIENT_ID}

spring:
  datasource:
    url: jdbc:postgresql://A01DBVL011.adeo.no:5432/familie-oppdrag

OPPDRAG_SERVICE_URL: https://wasapp.adeo.no/cics/services/simulerFpServiceWSBinding
SECURITYTOKENSERVICE_URL: https://sts.adeo.no/SecurityTokenServiceProvider/
