no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${OPPDRAG_CLIENT_ID}
    cookie_name: azure_token

oppdrag.mq:
  queuemanager: QM1
  send: DEV.QUEUE.1
  mottak: DEV.QUEUE.1
  avstemming: DEV.QUEUE.2
  channel: DEV.ADMIN.SVRCONN
  hostname: localhost
  port: 1414
  user: admin
  password: passw0rd
  enabled: true

spring.datasource:
  url: jdbc:postgresql://postgres-oppdrag:5432/familieoppdrag
  username: familie
  password: familie-pwd

ACCEPTED_CLIENTS: ${BA_SAK_CLIENT_ID}