oppdrag.mq:
  queuemanager: QM1
  send: DEV.QUEUE.1
  mottak: DEV.QUEUE.1
  avstemming: DEV.QUEUE.2
  channel: DEV.ADMIN.SVRCONN
  hostname: localhost
  port: 1414
  user: admin
  password: passw0rd
  enabled: true

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${CLIENT_ID}
    cookie_name: azure_token

ACCEPTED_CLIENTS: ${BA_SAK_CLIENT_ID}, ${EF_SAK_CLIENT_ID}

spring.datasource.url: jdbc:postgresql://0.0.0.0:5432/familie-oppdrag
spring.datasource.username: postgres
spring.datasource.password: test

OPPDRAG_SERVICE_URL: #Mockes ut lokalt
SECURITYTOKENSERVICE_URL: https://localhost:8063/soap/SecurityTokenServiceProvider/
CREDENTIAL_USERNAME: not-a-real-srvuser
CREDENTIAL_PASSWORD: not-a-real-pw