# NB! Dette skal ikke skrus på i produksjon før avstemming er på plass!
# TODO: Koble om til generell kø OB04_OPPDRAG_XML og lage en egen kanal for familie_oppdrag
oppdrag.mq:
  queuemanager: MPLSC02
  queuename: QA.P231.OB04_OPPDRAG_FP_XML
  channel: P_FPSAK
  hostname: a01apvl063.adeo.no
  port: 1414
  user: ${MQ_SRVBRUKER}
  password: ${MQ_PASSWORD}
  enabled: false
